spring.application.name=envio-core-engine

# Database Connection Settings
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/envio_db}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:password123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true